# Generated by Django 5.1.2 on 2025-11-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія кампанії',
                'verbose_name_plural': 'Категорії кампаній',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(max_length=280, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Повний опис')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('in_progress', 'У процесі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('location_name', models.CharField(max_length=255, verbose_name='Локація (назва)')),
                ('location_address', models.CharField(blank=True, max_length=500, verbose_name='Адреса локації')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Область/регіон')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Гривні. Якщо не потрібен грошовий збір, залиште порожнім.', max_digits=12, null=True, verbose_name='Цільова сума')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Накопичено')),
                ('required_volunteers', models.PositiveIntegerField(default=0, verbose_name='Необхідна кількість волонтерів')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактний email')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Контактний телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Координатор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.campaigncategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Кампанія',
                'verbose_name_plural': 'Кампанії',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CampaignShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва зміни')),
                ('description', models.TextField(blank=True, verbose_name='Опис завдань')),
                ('start_at', models.DateTimeField(verbose_name='Початок зміни')),
                ('end_at', models.DateTimeField(verbose_name='Завершення зміни')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Кількість місць')),
                ('status', models.CharField(choices=[('open', 'Набір триває'), ('full', 'Набір закрито'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='open', max_length=20, verbose_name='Статус')),
                ('location_details', models.CharField(blank=True, max_length=255, verbose_name='Деталі локації')),
                ('instructions', models.TextField(blank=True, verbose_name='Інструкції для волонтерів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='campaigns.campaign', verbose_name='Кампанія')),
            ],
            options={
                'verbose_name': 'Зміна',
                'verbose_name_plural': 'Зміни',
                'ordering': ('start_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва етапу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Етап виконано')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Очікувана дата завершення')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='campaigns.campaign', verbose_name='Кампанія')),
            ],
            options={
                'verbose_name': 'Етап кампанії',
                'verbose_name_plural': 'Етапи кампанії',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('approved', 'Підтверджено'), ('declined', 'Відхилено'), ('withdrawn', 'Скасовано волонтером')], default='approved', max_length=20, verbose_name='Статус участі')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campaigns.campaignshift', verbose_name='Зміна')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Призначення волонтера на зміну',
                'verbose_name_plural': 'Призначення волонтерів на зміни',
                'ordering': ('shift__start_at',),
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, verbose_name='Мотивація')),
                ('experience', models.TextField(blank=True, verbose_name='Попередній досвід')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('approved', 'Підтверджено'), ('declined', 'Відхилено'), ('withdrawn', 'Скасовано волонтером')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campaigns.campaign', verbose_name='Кампанія')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_applications', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Заявка волонтера',
                'verbose_name_plural': 'Заявки волонтерів',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'category', 'region'], name='campaigns_c_status_53577e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='campaigns_c_slug_a60613_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignshift',
            index=models.Index(fields=['campaign', 'start_at'], name='campaigns_c_campaig_d0d368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('shift', 'volunteer')},
        ),
        migrations.AlterUniqueTogether(
            name='volunteerapplication',
            unique_together={('campaign', 'volunteer')},
        ),
    ]
