# Generated by Django 5.1.2 on 2025-11-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Референс')),
                ('provider', models.CharField(choices=[('monobank', 'Monobank'), ('privatbank', 'PrivatBank'), ('manual', 'Ручний внесок')], default='monobank', max_length=20, verbose_name='Провайдер')),
                ('external_id', models.CharField(blank=True, help_text='Ідентифікатор платежу у сторонньому сервісі.', max_length=120, verbose_name='Зовнішній ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('processing', 'Обробляється'), ('succeeded', 'Успішно сплачено'), ('failed', 'Помилка оплати'), ('refunded', 'Повернено кошти')], default='pending', max_length=20, verbose_name='Статус')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email платника')),
                ('payer_name', models.CharField(blank=True, max_length=255, verbose_name="Ім'я платника")),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Коментар')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Сире повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign', verbose_name='Кампанія')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Донор')),
            ],
            options={
                'verbose_name': 'Пожертва',
                'verbose_name_plural': 'Пожертви',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['campaign', 'status'], name='payments_do_campaig_e69d5c_idx'), models.Index(fields=['provider', 'external_id'], name='payments_do_provide_725cc8_idx')],
            },
        ),
    ]
